### ISSUE TITLE
关于RETA-LLM下的environment.yml文件的修改

### ISSUE THREAD

**Issue by yinhong-hu** [RUC-GSAI/YuLan-IR#8]
作者你好，我发现该项目文件中的environment.yml中每个包都有详细信息，这是从机器上导出环境时附带的，当他人使用该文件进行安装环境时，可能会报错，我将每个的详细信息删除，以便他人可以直接使用该yml文件进行安装，我已向你发送pull request，请留意一下。谢谢

**Comment by rucliujn** [comment]
谢谢你的纠错，刚刚merge了你的PR。
